### ISSUE TITLE
Анализ рынка (29.02)

### ISSUE THREAD

**Issue by EvaPril** [EvaPril/Cat-chy-code-IT-impossible#54]
- Какие есть сайты портфолио
- Какой функционал у них (в том числе какие фильтры)
- Какое содержание
- главные конкуренты

По пользователям:

- что для нанимателей есть
- что для исполнителей
- люди каких профессий пользуются общими сайтами портфолио
- а каких профессий люди предпочитают индивидуальные сайты использовать (например, фотографы некоторые, дизайнеры....)

Сделать выводы:

- Кто ЦА
- Что ЦА нужно 
- критерии успешности проекта

Для ЦА отсутствие сайта с портфолио реальная проблема, в решении которой они нуждаются и к нему стремятся.

**Comment by EvaPril** [comment]
Антон и Вика, распределите между собой сами. Если не получится - го ко мне.
Вика, как уже аналитик с каким-то опытом, посмотри на задачу и расширь по необходимости.

Самое главное выяснить для кого отсутствие сайта с портфолио реальная проблема, в решении которой они нуждаются и к нему стремятся. И не решается ли проблема каким другим более простым и доступным способом у предполагаемой ЦА (а то мало ли они неплохо себя чувствуют с существующими решениями) 

Оформлять можно как угодно - хоть док, хоть преза. Желательно, ссылочки на все сайты сохранить, а информацию структурировать

**Comment by MortemD** [comment]
Помогу немного аналитикам и скинуть список сайтов которые могут быть нашими конкурентами + это в целом сайты похожие по нашей идее
1) [https://www.awwwards.com](https://vk.com/away.php?to=https%3A%2F%2Fwww.awwwards.com&cc_key=)
2) [https://cssdesignawards.com](https://vk.com/away.php?to=https%3A%2F%2Fcssdesignawards.com&cc_key=)
3) [https://onepagelove.com](https://vk.com/away.php?to=https%3A%2F%2Fonepagelove.com&cc_key=)
4) [https://dribbble.com](https://vk.com/away.php?to=https%3A%2F%2Fdribbble.com&cc_key=) (главный конкурент?)
5) [https://www.designspiration.com](https://vk.com/away.php?to=https%3A%2F%2Fwww.designspiration.com&cc_key=)
6) [https://www.curated.design/?category=shops](https://vk.com/away.php?to=https%3A%2F%2Fwww.curated.design%2F%3Fcategory%3Dshops&cc_key=)
8) [https://mobbin.com/browse/ios/apps?sort=publishedAt](https://vk.com/away.php?to=https%3A%2F%2Fmobbin.com%2Fbrowse%2Fios%2Fapps%3Fsort%3DpublishedAt&cc_key=)
9) [https://savee.it](https://vk.com/away.php?to=https%3A%2F%2Fsavee.it&cc_key=)
10) [https://calltoinspiration.com](https://vk.com/away.php?to=https%3A%2F%2Fcalltoinspiration.com&cc_key=)
11) [https://refero.design/pagetypes](https://vk.com/away.php?to=https%3A%2F%2Frefero.design%2Fpagetypes&cc_key=)
12) [https://httpster.net](https://vk.com/away.php?to=https%3A%2F%2Fhttpster.net&cc_key=)
13) [https://land-book.com](https://vk.com/away.php?to=https%3A%2F%2Fland-book.com&cc_key=)
14) [https://practicedesign.io](https://vk.com/away.php?to=https%3A%2F%2Fpracticedesign.io&cc_key=)

**Comment by EvaPril** [comment]
В файле на гугл коммы оставила.
 Еще надо добавить инфу в соответствии с презентацией. 

 //Боли ЦА – это страх, дискомфорт или неуверенность, которые испытывают потребители из-за возникшей и нерешенной проблемы. Если грамотно описать проблему, то можно попасть в цель и донести до них ценность товаров.
Что-то в духе какую проблему им очень надо решить, они готовы пользоваться решениям, но пока их нет проблема приносит "такую-то" боль 

[Dlya_1_vstrechi.pptx](https://github.com/EvaPril/Cat-chy-code-IT-impossible/files/14436132/Dlya_1_vstrechi.pptx)

**Comment by kopityle** [comment]
> //Боли ЦА – это страх, дискомфорт или неуверенность, которые испытывают потребители из-за возникшей и нерешенной проблемы. Если грамотно описать проблему, то можно попасть в цель и донести до них ценность товаров. Что-то в духе какую проблему им очень надо решить, они готовы пользоваться решениям, но пока их нет проблема приносит "такую-то" боль



В док Аналитика добавила чувства и переживания ЦА

**Comment by EvaPril** [comment]
А что там по русским аналогам? Вы посмотрели?
