### ISSUE TITLE
Анализ рынка для доп идеи (29.02)

### ISSUE THREAD

**Issue by EvaPril** [EvaPril/Cat-chy-code-IT-impossible#55]
Доб идея - это сайт для вдохновения и подборок полезных сайтов. Пока в понах ее совместить с основной

Какие есть сайты на эту тему
Какой функционал у них (в том числе какие фильтры)
главные конкуренты

По пользователям:

кто использует
люди каких профессий пользуются

Сделать выводы:

Кто ЦА
Что ЦА нужно
критериев успешности проекта

Для ЦА отсутствие сайта с такого реальная проблема, в решении которой они нуждаются и к нему стремятся.

**Comment by MortemD** [comment]
Помогу немного аналитикам и скинуть список сайтов которые могут быть нашими конкурентами + это в целом сайты похожие по нашей идее
1) [https://www.awwwards.com](https://vk.com/away.php?to=https%3A%2F%2Fwww.awwwards.com&cc_key=)
2) [https://cssdesignawards.com](https://vk.com/away.php?to=https%3A%2F%2Fcssdesignawards.com&cc_key=)
3) [https://onepagelove.com](https://vk.com/away.php?to=https%3A%2F%2Fonepagelove.com&cc_key=)
4) [https://dribbble.com](https://vk.com/away.php?to=https%3A%2F%2Fdribbble.com&cc_key=) (главный конкурент?)
5) [https://www.designspiration.com](https://vk.com/away.php?to=https%3A%2F%2Fwww.designspiration.com&cc_key=)
6) [https://www.curated.design/?category=shops](https://vk.com/away.php?to=https%3A%2F%2Fwww.curated.design%2F%3Fcategory%3Dshops&cc_key=)
8) [https://mobbin.com/browse/ios/apps?sort=publishedAt](https://vk.com/away.php?to=https%3A%2F%2Fmobbin.com%2Fbrowse%2Fios%2Fapps%3Fsort%3DpublishedAt&cc_key=)
9) [https://savee.it](https://vk.com/away.php?to=https%3A%2F%2Fsavee.it&cc_key=)
10) [https://calltoinspiration.com](https://vk.com/away.php?to=https%3A%2F%2Fcalltoinspiration.com&cc_key=)
11) [https://refero.design/pagetypes](https://vk.com/away.php?to=https%3A%2F%2Frefero.design%2Fpagetypes&cc_key=)
12) [https://httpster.net](https://vk.com/away.php?to=https%3A%2F%2Fhttpster.net&cc_key=)
13) [https://land-book.com](https://vk.com/away.php?to=https%3A%2F%2Fland-book.com&cc_key=)
14) [https://practicedesign.io](https://vk.com/away.php?to=https%3A%2F%2Fpracticedesign.io&cc_key=)

**Comment by kopityle** [comment]
> 4. [https://dribbble.com](https://vk.com/away.php?to=https%3A%2F%2Fdribbble.com&cc_key=) (главный конкурент?)
Буду благодарна,  если скажешь, почему именно он главный конкурент. Функционалом?Это очень поможет аналитике. Заранее пасиба

**Comment by MortemD** [comment]
Мне кажется, что это наш конкурент (главный), потому что это один из самых популярных ресурсов на эту тему (есть ещё pinterest,  который самый популярный, но он чуть в другой сфере, хотя и его можете глянуть)

**Comment by MortemD** [comment]
Ну а функционал крутой у 8 сайта, там можно картинки по цвету искать)

**Comment by EvaPril** [comment]
А на сайтах конкурентов есть проверка повторов? Например, загрузил чел свой сайт для портфолио - и сайту как бы присвоилось авторство. А дальше его в портфолио добавлять нельзя, а в подборках идет указание на автора

**Comment by MortemD** [comment]
Про это не могу сказать, но вероятнее всего есть нечто на подобие.
