### ISSUE TITLE
Презентация по аналитике (02.03)

### ISSUE THREAD

**Issue by EvaPril** [EvaPril/Cat-chy-code-IT-impossible#56]
по этой презе и имеющейся аналитике сделать презу для куратора https://vk.com/doc810555718_673595548?hash=L2odsA0LIgwYkodDi7C1smz1bzWvZUYPJofy3mu50ZH&dl=3s7z9ce0ziHXsLTc89z5dB61lMsYjqFGIzkkko5EQf0

Текст читабельный.

**Comment by kopityle** [comment]
Нашла новую нейронку для создания презентации--https://gamma.app/  . Некрасиво получилось по распределению работы, я кинула Антона и он сам создавал презентацию,аналитику. За что ему большое спасибо. Презентацию с помощью нейронки переделала под требования(2-3 слайда максимум) и в аналитике сделала текст более связным,красивым. Если слайд по конкурентам недостаточно информативный, попробую раскрыть

**Comment by EvaPril** [comment]
> Нашла новую нейронку для создания презентации--https://gamma.app/ . Некрасиво получилось по распределению работы, я кинула Антона и он сам создавал презентацию,аналитику. За что ему большое спасибо. Презентацию с помощью нейронки переделала под требования(2-3 слайда максимум) и в аналитике сделала текст более связным,красивым. Если слайд по конкурентам недостаточно информативный, попробую раскрыть

Думаю, и варант антона подходит, т.к. информативных то у него 4 - остальные связки. Но у тебя суть читается проще  
С документом у меня та два небольших вопроса, которые даже решения могут не требовать, но глянь там коммы. А в остальном, Вика - ты солнышко!
