### ISSUE TITLE
Опрос 22.03.24

### ISSUE THREAD

**Issue by EvaPril** [EvaPril/Cat-chy-code-IT-impossible#60]
1. темная тема. Мешает ли пользователю в ней наличие неприглушенного белого и что в ней ему важно
2. если пользователь пользуется сайтами с фильтрами и тегами, что ему в них важно. Много ли надо для удобства. Пополняются ли их библиотеки. Хочет ли иногда сам дополнить... (что-то в этом духе)

**Comment by kopityle** [comment]
https://forms.yandex.ru/u/65f9aff5068ff02345dcf717/ Черновой вариант опроса. Помимо вопросов выше добавила парочку своих. Мб еще в группу нашу можно скинуть, предложения получить

**Comment by kopityle** [comment]
https://forms.yandex.ru/u/65f9aff5068ff02345dcf717/ дублирую ссыль. Добавила вопрос про курс, "За кем Вы бы пришли на наш сайт в первую очередь?", уточнила вопрос про теги (нейронка прикольно придумала, я бы так сама не смогла), 

![Image](https://github.com/EvaPril/Cat-chy-code-IT-impossible/assets/148278339/d34de107-352d-4e3a-8a08-60d426fcedbc)



![Image](https://github.com/EvaPril/Cat-chy-code-IT-impossible/assets/148278339/cf30e7e0-af38-4deb-af6d-e865d67e7b14)

**Comment by EvaPril** [comment]
Вопрос про темную тему и белый появился отсюда. А так с картинкой классная идея. Главное, чтобы этим сильно не палили изюм проекта
![Image](https://github.com/EvaPril/Cat-chy-code-IT-impossible/assets/147942582/cad0c585-f094-4639-b67e-bb38919db564)
