### ISSUE TITLE
Провести опрос для узкой аудитории среди релевантных респондентов 26.04.24

### ISSUE THREAD

**Issue by EvaPril** [EvaPril/Cat-chy-code-IT-impossible#64]

**Comment by kopityle** [comment]
Про фоновую тему переделала чутка вопрос,можешь ознакомитьсяЗа кем/чем Вы бы пришли на наш сайт-портфолио в первую очередь?
Здесь можно разделить на два. Вам приходилось искать специалиста? И имело ли значение наличие портфолио (да, у всех кого искал, нет, только у некоторых...) - ну тип такого
Ну и отдельно про искали ли вдохновения среди работ других людей и каких специальностей.

На вопрос о пользуетесь ли сайтом портфолио и агалогами, можно варианты накидать (что ты нашел, Пинтерест ещё, инсту с пометкой о запрещенке, гитхаб и т.д. с вариантом "другое"

Все, больше у меня комментариев нет
Объясню, откуда это - чтобы мы максимально поняли, что люди имели ввиду, кто они и чем занимаются, и чтобы людям было удобно заполнять. Если у тебя мысли на этот счёт есть, то тоже давай

**Comment by kopityle** [comment]
Про фоновую тему переделала чутка вопрос,можешь ознакомиться
>За кем/чем Вы бы пришли на наш сайт-портфолио в первую очередь?
Здесь можно разделить на два. Вам приходилось искать специалиста?

думаю,это отображено вариантом ответа в вопросе  Что бы Вы хотели разместить на сайте-портфолио?  --свой проект,на который нужны люди

 >И имело ли значение наличие портфолио (да, у всех кого искал, нет, только у некоторых...) - ну тип такого

По моему мнению, в вопросе Как вы считаете, насколько важно иметь сайт-портфолио в профессиональной деятельности? можно узнать, было ли важно портфолио для человека (если нет, то он просто ответит "нет"). И да, опережая, я не вижу смысла спрашивать, нужно ли им было портфолио (Не сайт), так как это может привести к дублированию вопросов, да и ответ очевиден,как по мне(ну какого человека примут без портфолио ).

>Ну и отдельно про искали ли вдохновения среди работ других людей и каких специальностей.

Добавила после вопроса За кем/чем Вы бы пришли на наш сайт-портфолио в первую очередь?

>На вопрос о пользуетесь ли сайтом портфолио и аналогами, можно варианты накидать (что ты нашел, Пинтерест ещё, инсту с пометкой о запрещенке, гитхаб и т.д. с вариантом "другое"

Добавила,брала из ру конкурентов+ то, что ты привела

**Comment by EvaPril** [comment]
>Про фоновую тему переделала чутка вопрос,можешь ознакомиться

Вариант. Но вопрос возник из-за другой страницы, на этой не видно того момента. к другой задаче скрин скинула (на этой вчера не отражался коммент)

>>За кем/чем Вы бы пришли на наш сайт-портфолио в первую очередь?
Здесь можно разделить на два. Вам приходилось искать специалиста?

>думаю,это отображено вариантом ответа в вопросе Что бы Вы хотели разместить на сайте-портфолио? --свой проект,на который нужны люди  

Я имела ввиду отделить с помощью доп вопроса тех, кто пользуется портфолио уже, вне зависимо от нас.  Не спрашивать из позиции, что пользуются или теоретически захотят пользоваться, идея им нравится и т.д., а выяснить так ли это.  

>И имело ли значение наличие портфолио (да, у всех кого искал, нет, только у некоторых...) - ну тип такого

Относилось к варианту с разделенным вопросом о поиске профессионалов, для более точного понимания уже существующего опыта, а не общих убеждений (ну, к примеру, чел уверен, что портфолио хорошо и надо всем, но сам, когда искал фотографа, обратил внимание только на отзывы). В целом, это вся тема с разделением - подстраховка для выявления того, что пользователям не надо, но они такие "ДА, КРУТО,  ХОЧУ!", а потом "ну нафиг оно мне, мне раньше удобно было". 

**В общем, вывод - отредачь там многострадальный вопрос про тему и запускай в массы.** Я еще своим покидаю не пекусам.
